In [1]:



import pandas as pd

In [2]:
pwd               # to get the location of pandas in directory

'/home/prince_singh/Desktop'

In [3]:
pd.read_csv('electronic-card-transactions-january-2021-csv-tables.csv')

,Series_reference,Period,Data_value,Suppressed,STATUS,UNITS,Magnitude,Subject,Group,Series_title_1,Series_title_2,Series_title_3,Series_title_4,Series_title_5
0,ECTA.S19A1,2001.03,2462.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
1,ECTA.S19A1,2002.03,17177.2,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
2,ECTA.S19A1,2003.03,22530.5,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
3,ECTA.S19A1,2004.03,28005.1,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
4,ECTA.S19A1,2005.03,30629.6,NaN,F,Dollars,6,Electronic Card Transactions (ANZSIC06) - ECT,Total values - Electronic card transactions A/...,Actual,RTS total industries,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17505,ECTQ.S4AXP,2019.12,43.6,NaN,F,Percent,0,Electronic Card Transactions (ANZSIC06) - ECT,Electronic card transactions by mean and propo...,Actual,Debit card usage as a proportion of total ECT ...,Proportion (%),NaN,NaN
17506,ECTQ.S4AXP,2020.03,42.6,NaN,F,Percent,0,Electronic Card Transactions (ANZSIC06) - ECT,Electronic card transactions by mean and propo...,Actual,Debit card usage as a proportion of total ECT ...,Proportion (%),NaN,NaN
17507,ECTQ.S4AXP,2020.06,36.3,NaN,F,Percent,0,Electronic Card Transactions (ANZSIC06) - ECT,Electronic card transactions by mean and propo...,Actual,Debit card usage as a proportion of total ECT ...,Proportion (%),NaN,NaN
17508,ECTQ.S4AXP,2020.09,39.2,NaN,F,Percent,0,Electronic Card Transactions (ANZSIC06) - ECT,Electronic card transactions by mean and propo...,Actual,Debit card usage as a proportion of total ECT ...,Proportion (%),NaN,NaN
17509,ECTQ.S4AXP,2020.12,38.6,NaN,F,Percent,0,Electronic Card Transactions (ANZSIC06) - ECT,Electronic card transactions by mean and propo...,Actual,Debit card usage as a proportion of total ECT ...,Proportion (%),NaN,NaN

In [5]:
df = pd.read_csv('electronic-card-transactions-january-2021-csv-tables.csv')

In [10]:
df2 = df.to_csv('new_name_electronic-card-transactions-january-2021-csv-tables.csv') #saving new file, in same location

In [12]:
 pd.read_excel('SampleData.xlsx')       # reading excel files

    Unnamed: 0 Unnamed: 1                                         Unnamed: 2
0          NaN        NaN                                                NaN
1          NaN        NaN                                                NaN
2          NaN        NaN                                                NaN
3          NaN        NaN                            Online Instruction Page
4          NaN        NaN                              Sample Data for Excel
5          NaN        NaN                                                NaN
6          NaN        NaN                                  Related tutorials
7          NaN        NaN                                 Named Excel Tables
8          NaN        NaN                                    Data Entry Tips
9          NaN        NaN                            More Excel Sample Files
10         NaN        NaN                                                NaN
11         NaN        NaN                       Related Contextures Products
12         NaN        NaN                     Contextures Excel Tools Add-in
13         NaN        NaN                               Data Entry Popup Kit
14         NaN        NaN                                                NaN
15         NaN        NaN  Get weekly Excel tips, tutorials, videos, and ...
16         NaN        NaN                       Contextures Excel Newsletter
17         NaN        NaN                                                NaN
18         NaN        NaN                                              Notes
19         NaN          â€¢  SalesOrders sheet has sales data for a fiction...
20         NaN          â€¢  The Total column could be changed to a formula...

In [14]:
df4 = pd.read_html('https://www.contextures.com/xlsampledata01.html')    #reading html file

In [25]:
df4[0]                                                            # DataFrame of html file

             0        1         2        3      4         5        6
0    OrderDate   Region       Rep     Item  Units  UnitCost    Total
1     1/6/2019     East     Jones   Pencil     95      1.99   189.05
2    1/23/2019  Central    Kivell   Binder     50     19.99   999.50
3     2/9/2019  Central   Jardine   Pencil     36      4.99   179.64
4    2/26/2019  Central      Gill      Pen     27     19.99   539.73
5    3/15/2019     West   Sorvino   Pencil     56      2.99   167.44
6     4/1/2019     East     Jones   Binder     60      4.99   299.40
7    4/18/2019  Central   Andrews   Pencil     75      1.99   149.25
8     5/5/2019  Central   Jardine   Pencil     90      4.99   449.10
9    5/22/2019     West  Thompson   Pencil     32      1.99    63.68
10    6/8/2019     East     Jones   Binder     60      8.99   539.40
11   6/25/2019  Central    Morgan   Pencil     90      4.99   449.10
12   7/12/2019     East    Howard   Binder     29      1.99    57.71
13   7/29/2019     East    Parent   Binder     81     19.99  1619.19
14   8/15/2019     East     Jones   Pencil     35      4.99   174.65
15    9/1/2019  Central     Smith     Desk      2    125.00   250.00
16   9/18/2019     East     Jones  Pen Set     16     15.99   255.84
17   10/5/2019  Central    Morgan   Binder     28      8.99   251.72
18  10/22/2019     East     Jones      Pen     64      8.99   575.36
19   11/8/2019     East    Parent      Pen     15     19.99   299.85
20  11/25/2019  Central    Kivell  Pen Set     96      4.99   479.04
21  12/12/2019  Central     Smith   Pencil     67      1.29    86.43
22  12/29/2019     East    Parent  Pen Set     74     15.99  1183.26
23   1/15/2020  Central      Gill   Binder     46      8.99   413.54
24    2/1/2020  Central     Smith   Binder     87     15.00  1305.00
25   2/18/2020     East     Jones   Binder      4      4.99    19.96
26    3/7/2020     West   Sorvino   Binder      7     19.99   139.93
27   3/24/2020  Central   Jardine  Pen Set     50      4.99   249.50
28   4/10/2020  Central   Andrews   Pencil     66      1.99   131.34
29   4/27/2020     East    Howard      Pen     96      4.99   479.04
30   5/14/2020  Central      Gill   Pencil     53      1.29    68.37
31   5/31/2020  Central      Gill   Binder     80      8.99   719.20
32   6/17/2020  Central    Kivell     Desk      5    125.00   625.00
33    7/4/2020     East     Jones  Pen Set     62      4.99   309.38
34   7/21/2020  Central    Morgan  Pen Set     55     12.49   686.95
35    8/7/2020  Central    Kivell  Pen Set     42     23.95  1005.90
36   8/24/2020     West   Sorvino     Desk      3    275.00   825.00
37   9/10/2020  Central      Gill   Pencil      7      1.29     9.03
38   9/27/2020     West   Sorvino      Pen     76      1.99   151.24
39  10/14/2020     West  Thompson   Binder     57     19.99  1139.43
40  10/31/2020  Central   Andrews   Pencil     14      1.29    18.06
41  11/17/2020  Central   Jardine   Binder     11      4.99    54.89
42   12/4/2020  Central   Jardine   Binder     94     19.99  1879.06
43  12/21/2020  Central   Andrews   Binder     28      4.99   139.72

In [27]:
from sqlalchemy import create_engine                                     # importing Sql package
engine = create_engine('sqlite:///:memory:')                        # creating a temporary engine in memory for sql

In [28]:
df_sql = df4[0].to_sql('My_SQL_Table', engine)                     #saving html dataframe to sql data

In [30]:
pd.read_sql('My_SQL_Table', con = engine)                           # reading sql data

    index           0        1         2        3      4         5        6
0       0   OrderDate   Region       Rep     Item  Units  UnitCost    Total
1       1    1/6/2019     East     Jones   Pencil     95      1.99   189.05
2       2   1/23/2019  Central    Kivell   Binder     50     19.99   999.50
3       3    2/9/2019  Central   Jardine   Pencil     36      4.99   179.64
4       4   2/26/2019  Central      Gill      Pen     27     19.99   539.73
5       5   3/15/2019     West   Sorvino   Pencil     56      2.99   167.44
6       6    4/1/2019     East     Jones   Binder     60      4.99   299.40
7       7   4/18/2019  Central   Andrews   Pencil     75      1.99   149.25
8       8    5/5/2019  Central   Jardine   Pencil     90      4.99   449.10
9       9   5/22/2019     West  Thompson   Pencil     32      1.99    63.68
10     10    6/8/2019     East     Jones   Binder     60      8.99   539.40
11     11   6/25/2019  Central    Morgan   Pencil     90      4.99   449.10
12     12   7/12/2019     East    Howard   Binder     29      1.99    57.71
13     13   7/29/2019     East    Parent   Binder     81     19.99  1619.19
14     14   8/15/2019     East     Jones   Pencil     35      4.99   174.65
15     15    9/1/2019  Central     Smith     Desk      2    125.00   250.00
16     16   9/18/2019     East     Jones  Pen Set     16     15.99   255.84
17     17   10/5/2019  Central    Morgan   Binder     28      8.99   251.72
18     18  10/22/2019     East     Jones      Pen     64      8.99   575.36
19     19   11/8/2019     East    Parent      Pen     15     19.99   299.85
20     20  11/25/2019  Central    Kivell  Pen Set     96      4.99   479.04
21     21  12/12/2019  Central     Smith   Pencil     67      1.29    86.43
22     22  12/29/2019     East    Parent  Pen Set     74     15.99  1183.26
23     23   1/15/2020  Central      Gill   Binder     46      8.99   413.54
24     24    2/1/2020  Central     Smith   Binder     87     15.00  1305.00
25     25   2/18/2020     East     Jones   Binder      4      4.99    19.96
26     26    3/7/2020     West   Sorvino   Binder      7     19.99   139.93
27     27   3/24/2020  Central   Jardine  Pen Set     50      4.99   249.50
28     28   4/10/2020  Central   Andrews   Pencil     66      1.99   131.34
29     29   4/27/2020     East    Howard      Pen     96      4.99   479.04
30     30   5/14/2020  Central      Gill   Pencil     53      1.29    68.37
31     31   5/31/2020  Central      Gill   Binder     80      8.99   719.20
32     32   6/17/2020  Central    Kivell     Desk      5    125.00   625.00
33     33    7/4/2020     East     Jones  Pen Set     62      4.99   309.38
34     34   7/21/2020  Central    Morgan  Pen Set     55     12.49   686.95
35     35    8/7/2020  Central    Kivell  Pen Set     42     23.95  1005.90
36     36   8/24/2020     West   Sorvino     Desk      3    275.00   825.00
37     37   9/10/2020  Central      Gill   Pencil      7      1.29     9.03
38     38   9/27/2020     West   Sorvino      Pen     76      1.99   151.24
39     39  10/14/2020     West  Thompson   Binder     57     19.99  1139.43
40     40  10/31/2020  Central   Andrews   Pencil     14      1.29    18.06
41     41  11/17/2020  Central   Jardine   Binder     11      4.99    54.89
42     42   12/4/2020  Central   Jardine   Binder     94     19.99  1879.06
43     43  12/21/2020  Central   Andrews   Binder     28      4.99   139.72